name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - requests=2.28.1
  - mlflow=2.0.1
  - wandb=0.13.7
  - pip:
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
