name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.28.1
  - mlflow=2.0.1
  - hydra-core=1.2.0
  - wandb=0.13.6
  - seaborn
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
