name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.0.1
  - ipython=8.7.0
  - notebook=6.5.2
  - ipykernel=6.19.2
  - cookiecutter=2.1.1
  - hydra-core=1.3.0
  - matplotlib=3.6.2
  - pandas=1.5.2
  - wandb=0.13.7
  - git=2.39.0
  - jupyterlab=3.5.1
